apiVersion: v1
kind: Service
metadata:
  namespace: node
  labels:
    app: node
  name: node
spec:
  ports:
  
    - protocol: TCP
      port: 8080
      targetPort: 8080
   
   
  selector:
    app: node
  type: ClusterIP
